In [9]:
import geopandas as gpd
institutions_dict = {'NG': {'institution_counts': {'Nottingham Trent University': 2, 'University of Nottingham': 1}, 'postcode_total': 3}, 'EH': {'institution_counts': {'University of Edinburgh': 2}, 'postcode_total': 2}, 'WC': {'institution_counts': {'London School of Economics & Political Science': 2, 'University College London': 1}, 'postcode_total': 3}, 'OX': {'institution_counts': {'University of Oxford': 2}, 'postcode_total': 2}, 'YO': {'institution_counts': {'University of York': 2}, 'postcode_total': 2}, 'LE': {'institution_counts': {'Loughborough University': 1, 'University of Leicester': 1}, 'postcode_total': 2}, 'BA': {'institution_counts': {'Bath Spa University': 1, 'University of Bath (The)': 1}, 'postcode_total': 2}, 'PO': {'institution_counts': {'The University of Chichester': 1}, 'postcode_total': 1}, 'SY': {'institution_counts': {'Prifysgol Aberystwyth': 1}, 'postcode_total': 1}, 'LL': {'institution_counts': {'Glyndwr University': 1}, 'postcode_total': 1}, 'BD': {'institution_counts': {'University of Bradford': 1}, 'postcode_total': 1}, 'EX': {'institution_counts': {'University of Exeter': 1}, 'postcode_total': 1}, 'FK': {'institution_counts': {'University of Stirling': 1}, 'postcode_total': 1}}
gdf_pc = gpd.read_file('geodata.gpkg', layer='postcode_areas')

In [10]:
gdf_pc

       cat pc_area                                           geometry
0        1      WD  POLYGON ((-0.13555 51.51064, -0.13561 51.51072...
1        2      WB  POLYGON ((-0.13561 51.51072, -0.13555 51.51064...
2        3      WH  POLYGON ((-0.15900 51.51265, -0.15904 51.51261...
3        4      WC  POLYGON ((-0.15904 51.51261, -0.15900 51.51265...
4        5      WK  POLYGON ((-0.15900 51.51265, -0.15872 51.51321...
...    ...     ...                                                ...
2722  2775      PA  POLYGON ((-6.19864 56.46146, -6.19770 56.46177...
2723  2776      PA  POLYGON ((-5.68619 56.16792, -5.68819 56.16696...
2724  2777      PA  POLYGON ((-5.84849 55.93919, -5.84775 55.93980...
2725  2778      SS  POLYGON ((0.66359 51.63649, 0.66170 51.63657, ...
2726  2779      BT  MULTIPOLYGON (((-7.46844 54.14083, -7.46864 54...

[2727 rows x 3 columns]

In [7]:
print(institutions_dict.keys())
print(institutions_dict['NG']["postcode_total"])
pc_counts = {key: institutions_dict[key]["postcode_total"] for key in institutions_dict.keys()}
print(pc_counts)

dict_keys(['NG', 'EH', 'WC', 'OX', 'YO', 'LE', 'BA', 'PO', 'SY', 'LL', 'BD', 'EX', 'FK'])
3
{'NG': 3, 'EH': 2, 'WC': 3, 'OX': 2, 'YO': 2, 'LE': 2, 'BA': 2, 'PO': 1, 'SY': 1, 'LL': 1, 'BD': 1, 'EX': 1, 'FK': 1}

In [16]:
def insert_count(row, col):
    return pc_counts.get(row[col], 0)

gdf_pc["count"] = 0
gdf_pc["count"] = gdf_pc.apply(insert_count, col='pc_area', axis=1)
gdf_pc

       cat pc_area                                           geometry  count
0        1      WD  POLYGON ((-0.13555 51.51064, -0.13561 51.51072...      0
1        2      WB  POLYGON ((-0.13561 51.51072, -0.13555 51.51064...      0
2        3      WH  POLYGON ((-0.15900 51.51265, -0.15904 51.51261...      0
3        4      WC  POLYGON ((-0.15904 51.51261, -0.15900 51.51265...      3
4        5      WK  POLYGON ((-0.15900 51.51265, -0.15872 51.51321...      0
...    ...     ...                                                ...    ...
2722  2775      PA  POLYGON ((-6.19864 56.46146, -6.19770 56.46177...      0
2723  2776      PA  POLYGON ((-5.68619 56.16792, -5.68819 56.16696...      0
2724  2777      PA  POLYGON ((-5.84849 55.93919, -5.84775 55.93980...      0
2725  2778      SS  POLYGON ((0.66359 51.63649, 0.66170 51.63657, ...      0
2726  2779      BT  MULTIPOLYGON (((-7.46844 54.14083, -7.46864 54...      0

[2727 rows x 4 columns]